/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:be658532-b51e-4c8a-8b90-edee61910515",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_2cfWX6cRw",
    "aws_user_pools_web_client_id": "2nf65g8rbg7ji42be9lvpda2m2",
    "oauth": {}
};


export default awsmobile;
